### ISSUE TITLE
🚨 Linter ERROR: No console

### ISSUE THREAD

**Issue by oieeaaaa** [jethrocabaluna/pokedex#1]
Found this under index.js `console.log('pokemons', pokemons);`.

It's considered best practice to remove console logs. Such messages are considered for debugging purposes.

See https://eslint.org/docs/rules/no-console.

😂✌️ whattup man!

**Comment by jethrocabaluna** [comment]
@oieeaaaa This is for an application exam. Hahaha!

**Comment by oieeaaaa** [comment]
LMAO. My bad. 

Well, Good luck sa exam mo bro. wish you the best!
